export const GET_ASSIGNMENTS_REQUESTED = "GET_ASSIGNMENTS_REQUESTED";
export const GET_ASSIGNMENTS_SUCCESS = "GET_ASSIGNMENTS_SUCCESS";
export const GET_ASSIGNMENTS_FAILED = "GET_ASSIGNMENTS_FAILED";

export const GET_SINGLE_ASSIGNMENT_REQUESTED =
  "GET_SINGLE_ASSIGNMENT_REQUESTED";
export const GET_SINGLE_ASSIGNMENT_SUCCESS = "GET_SINGLE_ASSIGNMENT_SUCCESS";
export const GET_SINGLE_ASSIGNMENT_FAILED = "GET_SINGLE_ASSIGNMENT_FAILED";

export const GET_PROJECTS_REQUESTED = "GET_PROJECTS_REQUESTED";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILED = "GET_PROJECTS_FAILED";

export const GET_SINGLE_PROJECT_REQUESTED = "GET_SINGLE_PROJECT_REQUESTED";
export const GET_SINGLE_PROJECT_SUCCESS = "GET_SINGLE_PROJECT_SUCCESS";
export const GET_SINGLE_PROJECT_FAILED = "GET_SINGLE_PROJECT_FAILED";

export const CREATE_PROJECT_REQUESTED = "CREATE_PROJECT_REQUESTED";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILED = "CREATE_PROJECT_FAILED";

export const GET_TEACHER_SELECTION_REQUESTED =
  "GET_TEACHER_SELECTION_REQUESTED";
export const GET_TEACHER_SELECTION_SUCCESS = "GET_TEACHER_SELECTION_SUCCESS";
export const GET_TEACHER_SELECTION_FAILED = "GET_TEACHER_SELECTION_FAILED";

export const GET_SINGLE_TEACHER_SELECTION_REQUESTED =
  "GET_SINGLE_TEACHER_SELECTION_REQUESTED";
export const GET_SINGLE_TEACHER_SELECTION_SUCCESS =
  "GET_SINGLE_TEACHER_SELECTION_SUCCESS";
export const GET_SINGLE_TEACHER_SELECTION_FAILED =
  "GET_SINGLE_TEACHER_SELECTION_FAILED";

export const GET_ACTIVE_PAGE = "GET_ACTIVE_PAGE";
export const SET_ACTIVE_PAGE = "SET_ACTIVE_PAGE";


export const SET_USER_INFO = "SET_USER_INFO";
export const SET_USER_STATUS = "SET_USER_STATUS";

export const SAVE_FORM_DATA = "SAVE_FORM_DATA";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";